### ISSUE TITLE
pip package needs to depend on sphinx

### ISSUE THREAD

**Issue by ldoktor** [autotest/autotest#1006]
Installing autotest without `sphinx` fails:

```
Collecting autotest>=0.16.2 (from -r requirements.txt (line 1))
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading autotest-0.16.2.tar.gz (4.4MB)
    100% |████████████████████████████████| 4.4MB 348kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5auOHK/autotest/setup.py", line 23, in <module>
        from sphinx.setup_command import BuildDoc
    ImportError: No module named sphinx.setup_command
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5auOHK/autotest/
```

**Comment by PandaWei** [comment]
Yes, I met this error and fix it by installing sphinx.

**Comment by PandaWei** [comment]
when I run 'pip install -r requirements.txt' for avocado-vt， it appears.

**Comment by ldoktor** [comment]
OMG I fixed it only to discover that it was already fixed by @clebergnu in https://github.com/autotest/autotest/commit/b06bac5a65d6fb9c873e025e01d20b98c7fafd07

I think it's time to release new minor release including this fix to avoid such problems...

**Comment by sathnaga** [comment]
@ldoktor Any updates on this, still this issue persists.

**Comment by ldoktor** [comment]
This problem is fixed in autotest master, but new autotest was not yet released in PYPI. @clebergnu when are you going to push the new version?

**Comment by sathnaga** [comment]
@clebergnu It would be good to have this fix fixed, as it has avocado-vt dependancy while installing.
Thanks in advance.

**Comment by lmr** [comment]
I suppose I'll do it, since you guys are not recommended to work on
autotest anymore.

**Comment by sathnaga** [comment]
@lmr Please do it, that would be great, Thanks in advance.

**Comment by ldoktor** [comment]
Hello @lmr, that would be great, @clebergnu is on vacation this week and I don't have permission to push to autotest pip.

**Comment by ldoktor** [comment]
Btw @lmr once you're in the releasing, would you please also release new aexpect? There were not many fixes, but at least the `safe` feature added recently is quite neat. Last release was almost year ago...

**Comment by lmr** [comment]
@ldoktor and @sathnaga: I've released pip packages for aexpect 1.2.0 and autotest 0.16.3:

https://pypi.python.org/pypi/aexpect
https://pypi.python.org/pypi/autotest

**Comment by ldoktor** [comment]
Great, @lmr, thank you!

**Comment by sathnaga** [comment]
@lmr Thanks a lot :-)
