### ISSUE TITLE
Windows guest fail to receive IP address from dhcp

### ISSUE THREAD

**Issue by ldoktor** [autotest/autotest#518]
Hi guys,

when developing a Windows test I got a lot of `No DHCP lease for MAC 9a:2b:2c:2d:2e:2f` or `...can't verify address...` messages. Followed by can't connect to guest test failures.

The problem is 100% reproducible (on my laptop):
1) Execute any test on Windows XP
2) killall qemu-kvm, rm -f env, rm -f /tmp/address_poll*
3) Execute any test on Windows XP

There is a simple fix, login to the machine (`vnc` or `nc` with the old IP address) and run `"ipconfig /renew"`. It returns error:
`An error occurred while renewing interface Local Area Connection 5 : Access is denied.` or
`An error occurred while renewing interface Local Area Connection 5 : Unable to contact your DHCP server. Request has timed out.`
but the IP address changes successfully and is recognized by autotest.

Funny was that by using GUI `Control Panel -> Network Connections -> Local Area ... -> Support -> Repair` didn't work, but cmd `ipconfig /renew` did.

My idea is that windows won't send dhcp request on boot when the old (previous run) address is still valid. But don't take me seriously, I don't understand Windows...

My laptop: Fedora 17, qemu-kvm-1.0.1-1.fc17.x86_64, current autotest git-next
Guest: Windows XP SP3

PS: I sometimes encounter broken bridge which requires to stop and start bridge (in  virt-manager) and then everything works fine. **This is not the case** and **bridge restart doesn't help**.

**Comment by ldoktor** [comment]
I don't really remember what this was about and I don't have this issue anymore...

**Comment by pomozoff** [comment]
@ldoktor So do I )
