### ISSUE TITLE
Not able to download GWT and install

### ISSUE THREAD

**Issue by sugunaML** [autotest/autotest#600]
Hi,

I have Ubuntu 12.10. The auto installation script did not work on this version, so tried with manual steps. While installing extra packages, I am facing with following issue:
autotest@ubuntu:/$sudo /usr/local/autotest/utils/build_externals.py
15:35:38 INFO | imported setuptools version 0.6.
15:35:38 INFO | A new Setuptools is not needed on this system.
15:35:38 INFO | imported MySQLdb version 1.2.3.
15:35:38 INFO | A new MySQLdb is not needed on this system.
15:35:38 INFO | imported django version 1.4.1.
15:35:38 INFO | A new Django is not needed on this system.
15:35:38 INFO | imported numpy version 1.6.2.
15:35:38 INFO | A new Numpy is not needed on this system.
15:35:38 INFO | imported matplotlib version 1.1.1.
15:35:38 INFO | A new Matplotlib is not needed on this system.
15:35:38 INFO | imported atfork version 0.1.2.
15:35:38 INFO | A new AtFork is not needed on this system.
15:35:38 INFO | imported paramiko version 1.7.7.1 (George).
15:35:38 INFO | A new Paramiko is not needed on this system.
15:35:38 INFO | imported simplejson version 2.6.1.
15:35:38 INFO | A new Simplejson is not needed on this system.
15:35:38 INFO | imported httplib2 version 0.6.0.
15:35:38 INFO | A new Httplib2 is not needed on this system.
15:35:38 INFO | gwt not installed for autotest
15:35:38 INFO | Fetching http://google-web-toolkit.googlecode.com/files/gwt-2.4.0.zip
15:36:41 WARNI| Could not fetch gwt package from http://google-web-toolkit.googlecode.com/files/gwt-2.4.0.zip.
15:36:41 ERROR| Unable to download gwt
15:36:41 INFO | compiling .py files in /usr/local/autotest/site-packages to .pyc
15:36:41 INFO | chmod -R a+rX '/usr/local/autotest/site-packages'
15:36:41 ERROR| Unable to download gwt
autotest@ubuntu:/$ sudo /usr/local/autotest/utils/compile_gwt_clients.py -a
15:37:44 ERROR| Unable to find GWT. You can use utils/build_externals.py to install it.
autotest@ubuntu:/$ ls /usr/local/autotest

I have internet connection and unlimited download access to my system. I have downloaded the package through browser from http://google-web-toolkit.googlecode.com/files/gwt-2.4.0.zip and installed through package manager Synaptic. Still the above problem exists. Please let me know what is wrong and how it could be installed.

Thanks
Suguna M L

**Comment by lufy90** [comment]
Hello~
I met the same problem.I know it's caused by the unique Chinese internet(we are locked in a big LAN)...Is there any other method to install(config) gwt for autotest????
Best wishes~

**Comment by lufy90** [comment]
I have get the zip file of gwt,where should I position it????
