### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by vinzy123** [autotest/autotest#615]
Hi,
When I open localhost/index.html
My index.html contains 

META HTTP-EQUIV="Refresh" CONTENT="1; URL=frontend/client/www/autotest.AfeClient/AfeClient.html"

which opens

http://localhost/frontend/client/www/autotest.AfeClient/AfeClient.html

I am getting the following error
(I guess something wrong with paths. I have explicitly copied frontend folder in /usr/local/autotest/apache/www folder)  

Received error 404 Not Found
Date: Fri, 22 Mar 2013 11:31:31 GMT
Server: Apache/2.2.22 (Ubuntu)
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 235
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>

<h3>Not Found</h3>

<p>The requested URL /afe/server/rpc/ was not found on this server.</p>

<hr>

<address>Apache/2.2.22 (Ubuntu) Server at localhost Port 80</address>
</body></html>

I am running on ubuntu 12.10 and how exactly the calling(of html pages) occurs?
and looking at the paths in https://github.com/autotest/autotest/wiki/WebFrontendHowTo
there is no folder named server in afe folder. Can anybody help?

Thanks

**Comment by Sumeet90** [comment]
Same issue occurred and I got 500 internal error while opening URL http://localhost/afe. I have found one POST API as http://localhost/afe/server/rpc/ returned with 500 error.

What I have done mistake during Autotest server installation.
Can anyone help me to resolve this issue?

**Comment by lmr** [comment]
@Sumeet90, many problems related to the autotest installation have the symptom of a 500 internal error. The most common nowadays is that you have installed an incorrect version of Django. Autotest still uses Django 1.5, but that version is outdated and most people won't have it easily installable in their target machines.

**Comment by Sumeet90** [comment]
@lmr Thank you so much for your reply. 500 internal error comes only while i clicking fronted tab. All others tab like 'Admin' and 'Results DB' are loaded properly. So is it related to Django's version issue ?

In my machine Django 1.3.1 version is installed so i will upgrade and check it.

**Comment by Sumeet90** [comment]
After upgrading Django 1.5 version but my issue is not resolved and getting same 500 inter server error.

**Comment by abitin** [comment]
how to solve this problem?!
