### ISSUE TITLE
Compile the GWT web frontends

### ISSUE THREAD

**Issue by piyushgupta11** [autotest/autotest#741]
As per the documentation to compile the Autotest web application and TKO frontend. we need to run /usr/local/autotest/utils/compile_gwt_clients.py -a.
but this is giving error saying :
the following clients failed
autotest.EmbeddedTkoClient
autotest.TkoClient
autotest.EmbeddedSpreadsheetClient
autotest.AfeClient

i even installed java-openjdk
it would be really needful if I can know what to do to solve this problem

**Comment by Sumeet90** [comment]
After running above command all client successfully complied but only autotest.AfeClient is not complied successfully as per below:


18:06:27 INFO | Compiling client autotest.EmbeddedTkoClient
18:06:27 DEBUG| Running 'java  -Xmx512M -cp "/usr/local/autotest/frontend/client/src:/usr/local/autotest/frontend/client/bin:/usr/local/autotest/site-packages/gwt/gwt-user.jar:/usr/local/autotest/site-packages/gwt/gwt-dev.jar" -Djava.awt.headless=true com.google.gwt.dev.Compiler -war "/usr/local/autotest/frontend/client/www.new"  autotest.EmbeddedTkoClient'
18:06:45 INFO | Compiling client autotest.AfeClient
18:06:45 DEBUG| Running 'java  -Xmx512M -cp "/usr/local/autotest/frontend/client/src:/usr/local/autotest/frontend/client/bin:/usr/local/autotest/site-packages/gwt/gwt-user.jar:/usr/local/autotest/site-packages/gwt/gwt-dev.jar" -Djava.awt.headless=true com.google.gwt.dev.Compiler -war "/usr/local/autotest/frontend/client/www.new"  autotest.AfeClient'
18:06:55 INFO | Error compiling autotest.AfeClient, leaving old client
18:06:55 INFO | Compiling client autotest.EmbeddedSpreadsheetClient
18:06:55 DEBUG| Running 'java  -Xmx512M -cp "/usr/local/autotest/frontend/client/src:/usr/local/autotest/frontend/client/bin:/usr/local/autotest/site-packages/gwt/gwt-user.jar:/usr/local/autotest/site-packages/gwt/gwt-dev.jar" -Djava.awt.headless=true com.google.gwt.dev.Compiler -war "/usr/local/autotest/frontend/client/www.new"  autotest.EmbeddedSpreadsheetClient'
18:07:15 INFO | Compiling client autotest.TkoClient
18:07:15 DEBUG| Running 'java  -Xmx512M -cp "/usr/local/autotest/frontend/client/src:/usr/local/autotest/frontend/client/bin:/usr/local/autotest/site-packages/gwt/gwt-user.jar:/usr/local/autotest/site-packages/gwt/gwt-dev.jar" -Djava.awt.headless=true com.google.gwt.dev.Compiler -war "/usr/local/autotest/frontend/client/www.new"  autotest.TkoClient'
18:07:42 ERROR| The following clients failed: autotest.AfeClient
