### ISSUE TITLE
Receive 500 after Autotest page is loaded successfully

### ISSUE THREAD

**Issue by objectkuan** [autotest/autotest#869]
![1](https://cloud.githubusercontent.com/assets/2225492/4042855/288c8978-2d09-11e4-8cb8-7629e03bebc3.jpg)

Received error 500 Internal Server Error
Date: Tue, 26 Aug 2014 10:04:44 GMT
Server: Apache/2.2.15 (CentOS)
Connection: close
Transfer-Encoding: Identity
Content-Type: text/html; charset=utf-8

Traceback (most recent call last):
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/core/handlers/base.py&quot;, line 88, in get_response
    response = middleware_method(request)
  File &quot;/home/hcho.ho/autotest/frontend/apache_auth.py&quot;, line 84, in process_request
    password=&#39;&#39;)
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/contrib/auth/**init**.py&quot;, line 49, in authenticate
    user = backend.authenticate(*_credentials)
  File &quot;/home/hcho.ho/autotest/frontend/apache_auth.py&quot;, line 21, in authenticate
    user = User.objects.get(username=username)
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/db/models/manager.py&quot;, line 151, in get
    return self.get_queryset().get(_args, **kwargs)
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/db/models/query.py&quot;, line 304, in get
    num = len(clone)
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/db/models/query.py&quot;, line 77, in **len**
    self._fetch_all()
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/db/models/query.py&quot;, line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/db/models/query.py&quot;, line 220, in iterator
    for row in compiler.results_iter():
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/db/models/sql/compiler.py&quot;, line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/db/models/sql/compiler.py&quot;, line 786, in execute_sql
    cursor.execute(sql, params)
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/db/backends/util.py&quot;, line 53, in execute
    return self.cursor.execute(sql, params)
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/db/utils.py&quot;, line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/db/backends/util.py&quot;, line 53, in execute
    return self.cursor.execute(sql, params)
  File &quot;/usr/lib/python2.6/site-packages/Django-1.6.6-py2.6.egg/django/db/backends/mysql/base.py&quot;, line 124, in execute
    return self.cursor.execute(query, args)
  File &quot;/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py&quot;, line 154, in execute
    charset = db.character_set_name()
InterfaceError: (0, &#39;&#39;)

**Comment by rrajeevan** [comment]
Just checking in - Is it compatible with Django 1.6 yet? :)

**Comment by lmr** [comment]
No, it's not.

**Comment by agraf** [comment]
Now? I keep hitting this and I can't downgrade to 1.5 easily.

**Comment by lmr** [comment]
@agraf, well, I'll check with @clebergnu if we can work on the Django 1.6 update.
