### ISSUE TITLE
job failed for ssh ping error 

### ISSUE THREAD

**Issue by snapout** [autotest/autotest#898]
Hello:
I am a benginner.
I installed the autotest web server successfully. But when I create a job, there comes errror when the job runs.It seems ssh ping error.I can run "./server/autotest-remote -m **\* -c client/tests/sleeptest/control" without error.Looking forward to your answer, thanks a lot!

belows is the status log:
12/02 02:14:57 ERROR|     utils:0153| [stderr] Permission denied, please try again.
12/02 02:14:57 ERROR|     utils:0153| [stderr] Permission denied, please try again.
12/02 02:14:57 ERROR|     utils:0153| [stderr] Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
12/02 02:15:23 ERROR|     utils:0153| [stderr] Permission denied, please try again.
12/02 02:15:23 ERROR|     utils:0153| [stderr] Permission denied, please try again.
12/02 02:15:23 ERROR|     utils:0153| [stderr] Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
12/02 02:15:48 ERROR|     utils:0153| [stderr] Permission denied, please try again.
12/02 02:15:48 ERROR|     utils:0153| [stderr] Permission denied, please try again.
12/02 02:15:48 ERROR|     utils:0153| [stderr] Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
12/02 02:15:48 ERROR|base_class:0381| verify failed
Traceback (most recent call last):
  File "/opt/autotest/client/shared/hosts/base_classes.py", line 376, in repair_software_only
    self.repair_filesystem_only()
  File "/opt/autotest/client/shared/hosts/base_classes.py", line 358, in repair_filesystem_only
    self.verify()
  File "/opt/autotest/client/shared/hosts/base_classes.py", line 206, in verify
    self.verify_connectivity()
  File "/opt/autotest/server/hosts/abstract_ssh.py", line 543, in verify_connectivity
    self.ssh_ping()
  File "/opt/autotest/server/hosts/abstract_ssh.py", line 423, in ssh_ping
    repr(e.result_obj))
AutoservSshPingHostError: command execution error
- Command: 
  /usr/bin/ssh -a -x  -o ControlPath=/tmp/_autotmp_xqm4PKssh-master/socket
  -o StrictHostKeyChecking=no -o ConnectTimeout=60 -o
  ServerAliveInterval=300 -l root -p 22 192.168.133.144 " true"
  Exit status: 255
  Duration: 25.2935519218

**Comment by Tiny2009** [comment]
I have the same problem, but how can I solve this problem

**Comment by lmr** [comment]
You can troubleshoot with actually logging into the machine with the same user autotest uses (that's usually `autotest`). with a normal ssh command. Explaining the actual command is beyond the scope of this old issue report.
