### ISSUE TITLE
raise error.AutotestError("Wrong version format '%s'" % (version)) 

### ISSUE THREAD

**Issue by Exorcium** [autotest/autotest#910]
Fedora 21, openvswitch installed from repo and has version:

ovs-vswitchd --version
ovs-vswitchd (Open vSwitch) 2.3.1-git3282e51
Compiled Jan 14 2015 16:48:53
OpenFlow versions 0x1:0x1

When in openvswitch.py using convert_version_to_int return:
raise error.AutotestError("Wrong version format '%s'" % (version))
cause version format is  2.3.1-git3282e51

Could you please fix it?
Thx.

**Comment by lmr** [comment]
I have this solution as a patch:

https://gist.github.com/lmr/2fcd911f57851b40691d

Is it possible that you could test it before I submit it as a patch?

**Comment by Exorcium** [comment]
I checked this fix. Now working correct. Nice work, thank you. Please commit this fix.

**Comment by lmr** [comment]
Fix pushed to master, thanks!
