### ISSUE TITLE
Setting up Autotest on docker.

### ISSUE THREAD

**Issue by omps** [autotest/autotest#933]
Has anyone tried integrating autotest on docker?

**Comment by lmr** [comment]
We have a test suite for docker written on top of autotest

https://github.com/autotest/autotest-docker

but I suspect that's not what you are looking for. By integration, you mean command line arguments that lets you run tests directly on a docker instance? If so, no, we don't have that, although we'd be happy to consider patchsets implementing them.

Although we did write one such plugin for our new project, avocado, that's going to be submitted for review in the next week or so.

**Comment by omps** [comment]
Hi lmr,

My question was more of having the autotest system running on a docker instance instead of writing specific test for docker. I am trying to work on it and would most likely post if any progress is made.

**Comment by cardinalsmurf** [comment]
I would also like to know if anyone is trying to containerize Autotest.  It would make installation so much easier.  I've been trying to install it myself but I keep running into issues.
