### ISSUE TITLE
which are the architectures supported by autotest

### ISSUE THREAD

**Issue by masoodahamed** [autotest/autotest#934]
Can any one tell me what are the architectures supported by autotest....???

**Comment by omps** [comment]
if by arch you mean 32 bit system or 64 bit Linux system, then I belive both these archs are supported, I have tested installation on these two but not sure about other as ARM, SPARC etc.

**Comment by masoodahamed** [comment]
yes, my question is whether it support ARM architecture or not....

**Comment by lmr** [comment]
`x86` in general, as well as `ppc`. About ARM, we don't have complete support, unfortunately. Trying to elaborate, we don't support bootloader control, and in general, we assume you actually have GNU coreutils in your embedded system instead of busybox so that the autotest server can control jobs in autotest clients.

**Comment by lmr** [comment]
For us, ARM is a bit tricky, as until recently we didn't have dedicated people and hardware to add ARM support. Now we have @ldoktor to help out with ARM support. Keep in mind though, that we are working on a new test framework that will succeed autotest, and that will have ARM as a supported platform.

**Comment by masoodahamed** [comment]
Can you suggest some other Framework that have support ARM??

**Comment by lmr** [comment]
https://www.linaro.org/projects/test-validation/

**Comment by ldoktor** [comment]
@masoodahamed, depends on what is your usecase. If you are focused on ARM-specific usage with various ARM platforms, then linaro's testsuite is probably the best choice. If you need to work with multiple architectures on well known ARM boards, then virttest might be better. ARM support is currently experimental. I'm working on `APM X-Gene CPU Potenza A3` which can run RHEL7sa. Most of the framework features should work, but lots of tests contain x86 specific handling and I'm in the process of generalizing them.
