### ISSUE TITLE
Unable to download gwt

### ISSUE THREAD

**Issue by zhaoguanghui** [autotest/autotest#961]
14:10:44 INFO | gwt not installed for autotest
14:10:44 INFO | Fetching http://google-web-toolkit.googlecode.com/files/gwt-2.5.1.zip
14:11:48 WARNI| Could not fetch gwt package from http://google-web-toolkit.googlecode.com/files/gwt-2.5.1.zip.
14:11:48 ERROR| Unable to download gwt
14:11:48 INFO | compiling .py files in /usr/local/autotest/site-packages to .pyc
Can't list /usr/local/autotest/site-packages
14:11:48 INFO | chmod -R a+rX '/usr/local/autotest/site-packages'
chmod: cannot access `/usr/local/autotest/site-packages': No such file or directory

I download gwt-2.5.1  but how to install it
and autotest said：access to http://192.168.22.22/afe but apache errlog [Wed Aug 26 13:21:59 2015] [error] [client 192.168.1.160] File does not exist: /var/www/html/afe  why

**Comment by lmr** [comment]
I don't know what happened on your system. It's best to try on a fresh system. And after all I've recently pushed gwt 2.7.0 to be used instead of 2.5.1, so I'd suggest updating your autotest. I'm going to close this ticket since I have no control on which links you can access and or download.  I've just tried here and I can download that package fine.

**Comment by zhaoguanghui** [comment]
At 2015-09-18 22:29:46, "Lucas Meneghel Rodrigues" <notifications@github.com> wrote:


I don't know what happened on your system. It's best to try on a fresh system. And after all I've recently pushed gwt 2.7.0 to be used instead of 2.5.1, so I'd suggest updating your autotest. I'm going to close this ticket since I have no control on which links you can access and or download. I've just tried here and I can download that package fine.

**Comment by abitin** [comment]
@zhaoguanghui 哥们，被墙了吧？你可以在个gwtproject官网上下载gwt2.7.0，然后将.zip文件放在/usr/local/autotest/Externalpackages文件夹下。然后再运行/usr/local/autotest/utils/build_externals.py
gwt就会自动解压安装在site-packages文件夹下了。
