### ISSUE TITLE
The following clients failed: autotest.AfeClient

### ISSUE THREAD

**Issue by Sumeet90** [autotest/autotest#974]
When I ran compile command as /usr/local/autotest/utils/compile_gwt_clients.py -a then it gives me below output and autotest.AfeClient compilation failed:

13:49:32 INFO | Compiling client autotest.EmbeddedTkoClient
13:49:32 DEBUG| Running 'java  -Xmx512M -cp "/usr/local/autotest/frontend/client/src:/usr/local/autotest/frontend/client/bin:/usr/local/autotest/site-packages/gwt/gwt-user.jar:/usr/local/autotest/site-packages/gwt/gwt-dev.jar" -Djava.awt.headless=true com.google.gwt.dev.Compiler -war "/usr/local/autotest/frontend/client/www.new"  autotest.EmbeddedTkoClient'
13:49:47 INFO | Compiling client autotest.AfeClient
13:49:47 DEBUG| Running 'java  -Xmx512M -cp "/usr/local/autotest/frontend/client/src:/usr/local/autotest/frontend/client/bin:/usr/local/autotest/site-packages/gwt/gwt-user.jar:/usr/local/autotest/site-packages/gwt/gwt-dev.jar" -Djava.awt.headless=true com.google.gwt.dev.Compiler -war "/usr/local/autotest/frontend/client/www.new"  autotest.AfeClient'
13:49:53 INFO | Error compiling autotest.AfeClient, leaving old client
13:49:53 INFO | Compiling client autotest.EmbeddedSpreadsheetClient
13:49:53 DEBUG| Running 'java  -Xmx512M -cp "/usr/local/autotest/frontend/client/src:/usr/local/autotest/frontend/client/bin:/usr/local/autotest/site-packages/gwt/gwt-user.jar:/usr/local/autotest/site-packages/gwt/gwt-dev.jar" -Djava.awt.headless=true com.google.gwt.dev.Compiler -war "/usr/local/autotest/frontend/client/www.new"  autotest.EmbeddedSpreadsheetClient'
13:50:09 INFO | Compiling client autotest.TkoClient
13:50:09 DEBUG| Running 'java  -Xmx512M -cp "/usr/local/autotest/frontend/client/src:/usr/local/autotest/frontend/client/bin:/usr/local/autotest/site-packages/gwt/gwt-user.jar:/usr/local/autotest/site-packages/gwt/gwt-dev.jar" -Djava.awt.headless=true com.google.gwt.dev.Compiler -war "/usr/local/autotest/frontend/client/www.new"  autotest.TkoClient'
13:50:33 ERROR| The following clients failed: autotest.AfeClient

And after that i open http://localhost/afe then got error as 404 not found.

It would be great if anyone can help to resolve this issue.

**Comment by lmr** [comment]
Once again, please verify the Django version in use. For the java problem, you have to execute manually the command your script printed:

    'java -Xmx512M -cp "/usr/local/autotest/frontend/client/src:/usr/local/autotest/frontend/client/bin:/usr/local/autotest/site-packages/gwt/gwt-user.jar:/usr/local/autotest/site-packages/gwt/gwt-dev.jar" -Djava.awt.headless=true com.google.gwt.dev.Compiler -war "/usr/local/autotest/frontend/client/www.new" autotest.AfeClient'

**Comment by Sumeet90** [comment]
Thank you very much for your help.

Now i am able to compiles autotest.AfeClient.

In my machine Django version is  1.5 but when I open frontend URL as http://localhost/afe then it gives 500 Internal Server Error.

Do you know anything that what I have done something wrong ?

**Comment by lmr** [comment]
I don't.
