### ISSUE TITLE
Unable to install grubby using boottool

### ISSUE THREAD

**Issue by aditijha** [autotest/autotest#983]
I have written some client tests that require client machine to reboot. While running the tests, I get the following:

18:27:20 INFO | Installing grubby because it was not found on this system
18:27:20 ERROR| grubby executable does not exist: "/sbin/grubby"
18:27:20 ERROR| insufficient permissions (read and execute) for grubby executable: "/sbin/grubby"
18:27:20 ERROR| _run_get_output error while running: "/sbin/grubby --version"
18:27:20 WARNI| Could not run grubby to fetch its version
18:27:20 WARNI| Could not detect current grubby version. It may be that you are running an unsupported version of grubby
18:27:20 ERROR| _run_get_output_err error while running: "/sbin/grubby --bootloader-probe"
18:27:20 ERROR| JOB ERROR: Unable to instantiate boottool: Failed to build grubby

using boottool.py to install grubby yields the following:

$ ./client/tools/boottool.py --debug=90 --grubby-install 
INFO: boottool: Installing grubby because it was not found on this system
ERROR: Grubby: grubby executable does not exist: "/sbin/grubby"
ERROR: Grubby: insufficient permissions (read and execute) for grubby executable: "/sbin/grubby"
ERROR: Grubby: _run_get_output error while running: "/sbin/grubby --version"
WARNING: Grubby: Could not run grubby to fetch its version
WARNING: Grubby: Could not detect current grubby version. It may be that you are running an unsupported version of grubby
ERROR: Grubby: _run_get_output_err error while running: "/sbin/grubby --bootloader-probe"
DEBUG: Grubby: No popt.h header present, skipping build
Traceback (most recent call last):
  File "./client/tools/boottool.py", line 2208, in <module>
    app.run()
  File "./client/tools/boottool.py", line 2004, in run
    install_grubby_if_necessary()
  File "./client/tools/boottool.py", line 681, in install_grubby_if_necessary
    path = grubby.grubby_install()
  File "./client/tools/boottool.py", line 1534, in grubby_install
    raise GrubbyInstallException('Failed to build grubby')
__main__.GrubbyInstallException: Failed to build grubby

Please help me resolve this issue.

**Comment by lmr** [comment]
The stack trace contains the reason of the problem:

    No popt.h header present, skipping build

If autotest can't find a new enough grubby to control the machine's build, it has to download grubby's source code and compile it. Therefore, the machines are required to have a working toolchain and header files necessary. For example, `popt.h` comes with `popt-devel` on recent Fedora.

The takeaway from this is: Verify that your machines have all dependencies necessary to build grubby, otherwise you'll continue to have the problem mentioned.

**Comment by aditijha** [comment]
Thanks for the response @lmr , I installed popt-devel and the error went away. However, the installation of grubby was still not successful. Here is the stack trace:


It may still be failing because of some missing dependency. Is the list of requirements here:
http://www.rpmfind.net/linux/RPM/sourceforge/f/fu/fuduntu-el/el6/current/TESTING/RPMS/grubby-8.11-1.el6.x86_64.html
same as the grubby dependencies? If not, can you please help me identify which packages need to be installed before grubby can be built?

**Comment by lmr** [comment]
result = subprocess.Popen(['make'],
                                  stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE)

According to the stack trace the problem is that your machine lacks `make`.

**Comment by lmr** [comment]
Now, considering that `make` is quite a basic package required for building miscellaneous types of programs, I ask you once again to review what's installed on those machines and make sure you can build grubby from a tarball.

**Comment by aditijha** [comment]
thanks
