### ISSUE TITLE
tools/results2junit.py throws AttributeError after successful job run w/ failed tests

### ISSUE THREAD

**Issue by cevich** [autotest/autotest#984]
Sometimes when a job fails in a particular way, this conversion script dies where it should just report the particular test as failed.  Reproducer ``client/results`` directory tarball is attached (rename it to results.tar.bz2) [results.docx](https://github.com/autotest/autotest/files/19762/results.docx).  I'll take a look at fixing this when I get a chance, unless someone else has a mind to and/or beats me to it :smile:

**Comment by cevich** [comment]
Reproducer output:
```
  ** Warning: The requested file (results/default/docker/subtests/docker_cli/version.7/debug/docker/subtests/docker_cli/version.7.DEBUG) does not exist.
Traceback (most recent call last):
  File "tools/results2junit.py", line 246, in <module>
    main(basedir, argv[1:])
  File "tools/results2junit.py", line 204, in main
    contents = text_clean(file_load(fid))
  File "tools/results2junit.py", line 50, in text_clean
    retval = retval.replace('\xe2\x80\x98', "'")
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by lmr** [comment]
OK @cevich, I've sent #988 to your appreciation, it should solve the problems you are having. That PR will remain open until you can take a look at it and verify it actually solves your problem.

**Comment by cevich** [comment]
OMG @lmr  you're my hero!  I didn't even get a chance to look into how to re-create the problem.  Okay, I'll get onto digging up a failing CI job and jam this patch in, see if the problem goes away...

**Comment by cevich** [comment]
Hrmmm, I just beat the crap out of the jobs that were hitting this all the time before, of course it's not reproducing it now :confounded:   Okay, guess I gotta look at the code to see if I can tickle the old code into breaking...

**Comment by cevich** [comment]
...okay, hmmm, so why might a test's debug log not exist....ahh ha!  It does exist, the path reported in the exception is wrong!

``results/default/docker/subtests/docker_cli/version.7/debug/docker/subtests/docker_cli/version.7.DEBUG``

That's totally the wrong path, it should be ``results/default/docker/subtests/docker_cli/version.7/debug/version.7.DEBUG`` (that file exists).  

Oddly, looking in the other ``docker_cli`` test subdirectories (from attached file), they all follow the same structure, so what's so special about this test (besides it's failing) that the path is totally wrong...

**Comment by cevich** [comment]
Ahhh, okay, methinks this is is just a PEBUAK.  I see:

```python
            if '.' in tname:
                (suite, name) = tname.split('.', 1)
            else:
                suite = tname
                name = tname
```

Because the conditionals go:  GOOD - nothing happens, FAIL - nothing happens, ERROR - tname is wrong.   That's what's causing this.

Now, TBH, I have no clue what the distinction of "suite" is here and I had no idea the '.' was important.  I'm just appending it and the number of the test in case there are multiple runs of the same test I need to distinguish between.  So this is an error on my part then, the ``results2junit.py`` code is/was fine IMHO.  Though your change does make it more robust.

I can easily change the character I use to something else, say '#' instead.  Though I'm curious, do you know if this 'suite' stuff is documented somewhere?  I think maybe I'm calling ``job.run_test()`` wrong, is there a ``suite=`` parameter or something?

Thanks again for looking into this.

**Comment by cevich** [comment]
Did some more playing and found it's the tests tag that does this.  For example, from within a step, if I do: 

``job.run_test(url=self.uri, tag=self.tag, timeout=int(self.timeout))``

Then autotest will represent that test's name (and in results) as ``%s.%s' % (uri, tag)``.  If I remove the tag parameter, I get just the ``uri`` as the name.  So the problem here seems to be results2junit is treating the '.' in the test name in a different special way than auto-test does.

Also, I looked through the documentation and didn't see much of anything on the 'suite' topic, so I'm not sure where that came from.  Though maybe someone is using it, so probably shouldn't kill it entirely.

What about a solution that tries the tag-based name if the suite-based name doesn't exist.  If that also doesn't exist, then your solution can take over with the 'file not found' detail?

```diff
diff --git a/client/tools/results2junit.py b/client/tools/results2junit.py
index ecf5142..684b892 100755
--- a/client/tools/results2junit.py
+++ b/client/tools/results2junit.py
@@ -188,20 +188,29 @@ def main(basedir, resfiles):
             tc.classname = 'autotest.%s' % suite
             tc.time = int(r[2])
             tests = tests + 1
+
+            fid = os.path.join(basedir, tname, 'debug', '%s.DEBUG' % tname)
+            if not os.path.exists(fid):
+                # tag also encoded with '.' delimeter, attempt with file
+                # based on name.tag if suite/name parsing file doesn't exist
+                fid = os.path.join(basedir, tname, 'debug',
+                                   '%s.DEBUG' % os.path.basename(r[0]))
+            debug_contents = file_load(fid)
+            if not debug_contents:
+                contents = 'Could not find debug file %s' % fid
+            else:
+                contents = text_clean(debug_contents)
+
             if r[1] == 'GOOD':
                 # success, we append the testcase without an error or fail
                 pass
             # Count NA as fails, disable them if you don't want them
             elif r[1] == 'TEST_NA':
                 failures = failures + 1
-                fid = os.path.join(basedir, tname, 'debug', '%s.DEBUG' % tname)
-                contents = text_clean(file_load(fid))
                 tcfailure = api.failureType(message='Test %s is Not Applicable: %s' % (tname,
                 tc.failure = tcfailure
             elif r[1] == 'ERROR':
                 failures = failures + 1
-                fid = os.path.join(basedir, tname, 'debug', '%s.DEBUG' % tname)
-                contents = text_clean(file_load(fid))
                 tcfailure = api.failureType(message='Test %s has failed' % tname, type_='Fail
                 tc.failure = tcfailure
             else:
```

(sorry, my repo isn't setup well to make another PR)

**Comment by cevich** [comment]
@lmr Did you get a chance to look at the above?

**Comment by lmr** [comment]
Sadly I didn't. Your idea looks sensible to me though. What about you compose a new PR with the combined approaches, so I can review and merge it?

**Comment by cevich** [comment]
@lmr: NP, okay, copy-paste, git apply, and bam: #989 :smile: 

(tested lightly, but not exhaustively)

**Comment by lmr** [comment]
Thanks, I'll take a look ASAP :)
