### ISSUE TITLE
http://localhost/afe/ results Error 500 Internal Server Error

### ISSUE THREAD

**Issue by stevenang** [autotest/autotest#999]
I setup an autotest server in Fedora 23 Server Edition.
During the installation, the script returned some error regarding the packages but I am able to handle that error and installed all necessary packages.

I was refer to the document (http://autotest.readthedocs.org/en/latest/main/sysadmin/AutotestServerInstallRedHat.html)

After compiling GWT and configure SELINUX, I restart the Apache Server to test the afe.
But when I tried to access http://localhost/afe/, the browser showed "Error 500 Internal Server Error".

I checked /var/log/httpd/erro_log and following error message was recored:

[Sun Jan 24 16:23:52.922011 2016] [wsgi:error] [pid 25955] [remote ::1:168] mod_wsgi (pid=25955): Exception occurred processing WSGI script '/usr/local/autotest/frontend/frontend.wsgi'.
[Sun Jan 24 16:23:52.922065 2016] [wsgi:error] [pid 25955] [remote ::1:168] Traceback (most recent call last):
[Sun Jan 24 16:23:52.922083 2016] [wsgi:error] [pid 25955] [remote ::1:168]   File "/usr/local/autotest/frontend/frontend.wsgi", line 25, in application
[Sun Jan 24 16:23:52.922156 2016] [wsgi:error] [pid 25955] [remote ::1:168]     return _application(environ, start_response)
[Sun Jan 24 16:23:52.922178 2016] [wsgi:error] [pid 25955] [remote ::1:168]   File "/usr/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
[Sun Jan 24 16:23:52.922233 2016] [wsgi:error] [pid 25955] [remote ::1:168]     return self.application(environ, start_response)
[Sun Jan 24 16:23:52.922241 2016] [wsgi:error] [pid 25955] [remote ::1:168]   File "/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
[Sun Jan 24 16:23:52.922323 2016] [wsgi:error] [pid 25955] [remote ::1:168]     self.load_middleware()
[Sun Jan 24 16:23:52.922331 2016] [wsgi:error] [pid 25955] [remote ::1:168]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 50, in load_middleware
[Sun Jan 24 16:23:52.922418 2016] [wsgi:error] [pid 25955] [remote ::1:168]     mw_class = import_string(middleware_path)
[Sun Jan 24 16:23:52.922425 2016] [wsgi:error] [pid 25955] [remote ::1:168]   File "/usr/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
[Sun Jan 24 16:23:52.922486 2016] [wsgi:error] [pid 25955] [remote ::1:168]     module = import_module(module_path)
[Sun Jan 24 16:23:52.922493 2016] [wsgi:error] [pid 25955] [remote ::1:168]   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
[Sun Jan 24 16:23:52.922525 2016] [wsgi:error] [pid 25955] [remote ::1:168]     __import__(name)
[Sun Jan 24 16:23:52.922541 2016] [wsgi:error] [pid 25955] [remote ::1:168] ImportError: No module named doc

I tried to search over the net but nothing useful found.
Can anyone help me to resolve this issue?

Thank you and good day.

**Comment by lmr** [comment]
On Sun, Jan 24, 2016 at 2:39 PM stevenang <notifications@github.com> wrote:

> I setup an autotest server in Fedora 23 Server Edition
> During the installation, the script returned some error regarding the
> packages but I am able to handle that error and installed all necessary
> packages
>

Autotest uses old versions of dependencies (Django is the most important
one) that will not work with recent distros, such as Fedora 23. You need to
use an old version of Django (1.5) to make autotest work at the moment.
And we don't have enough resources to port it over the most recent version,
so I can't give you an ETA for that.

>

**Comment by stevenang** [comment]
Thank you for the reply.  I already manage to solve the issue by installing Django 1.5.

**Comment by lufy90** [comment]
Hi~
My Django is 1.5.12,I encounter the same issue,should I install a lower version of Django??
Help~~~~
